// Code generated by github.com/willabides/gqltesthandler/cmd/gqltesthandler. DO NOT EDIT.

package usertest

import (
	"net/http"
	"sync"
)

// TestHandler is a mock GraphQL HTTP handler for testing.
// Set expectations with Expect methods, then use as an http.Handler.
type TestHandler struct {
	tb      TB
	handler http.Handler

	mu     sync.Mutex
	served bool

	getUserExpectResponses    expectResponses[GetUserVariables, getUserResult]
	createUserExpectResponses expectResponses[CreateUserVariables, createUserResult]
}

func (s *TestHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	s.handler.ServeHTTP(w, r)
}

// NewTestHandler creates a new TestHandler for use in tests.
func NewTestHandler(tb TB) *TestHandler {
	th := &TestHandler{tb: tb}
	th.handler = &testServer{tb: tb, handler: th}
	return th
}

// markServed records that the handler has processed a request. Once true,
// Reset and Reset<OpName> refuse to wipe state.
func (s *TestHandler) markServed() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.served = true
}

// Reset wipes all registered expectations and defaults on this handler and
// clears any pending cleanup errors so previously-unmet expectations will not
// fail the test. Reset records an error via tb.Errorf and leaves state
// untouched if the handler has already served any request (checked
// handler-wide, not per-operation), so it is safe to call only during test
// setup. The served-check and the clear are performed atomically — no
// request can mark the handler served while a Reset is in progress.
func (s *TestHandler) Reset() {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.served {
		s.tb.Errorf("TestHandler.Reset called after handler has served at least one request")
		return
	}
	s.getUserExpectResponses.clear()
	s.createUserExpectResponses.clear()
}

// getUserResult is the result interface for the GetUser operation.
type getUserResult interface {
	writeGetUserResult(w http.ResponseWriter, vars GetUserVariables) error
}

type getUserDataResult struct {
	data GetUserResponse
}

func (r getUserDataResult) writeGetUserResult(w http.ResponseWriter, _ GetUserVariables) error {
	return writeGraphQLData(w, r.data)
}

type getUserErrorResult struct {
	errors []GraphQLError
}

func (r getUserErrorResult) writeGetUserResult(w http.ResponseWriter, _ GetUserVariables) error {
	return writeGraphQLErrors(w, r.errors)
}

type getUserRawResult struct {
	fn func(GetUserVariables, http.ResponseWriter)
}

func (r getUserRawResult) writeGetUserResult(w http.ResponseWriter, vars GetUserVariables) error {
	r.fn(vars, w)
	return nil
}

// GetUserExpectation is a builder for setting the response of a GetUser
// expectation or default. Use ExpectGetUser or DefaultGetUser on
// TestHandler to obtain one.
type GetUserExpectation struct {
	handler   *TestHandler
	vars      GetUserVariables
	opts      []ExpectOption
	isDefault bool
}

func (b *GetUserExpectation) register(resp getUserResult) {
	if b.isDefault {
		b.handler.getUserExpectResponses.setDefault(resp)
		return
	}
	b.handler.getUserExpectResponses.expect(b.handler.tb, b.vars, nil, resp, b.opts...)
}

// Respond sets the response data. For an ExpectGetUser builder this
// registers a concrete expectation; for a DefaultGetUser builder this
// replaces the per-operation default.
func (b *GetUserExpectation) Respond(data GetUserResponse) {
	b.register(getUserDataResult{data: data})
}

// RespondError sets the response to return GraphQL errors. For an
// ExpectGetUser builder this registers a concrete expectation; for a
// DefaultGetUser builder this replaces the per-operation default.
func (b *GetUserExpectation) RespondError(errors ...GraphQLError) {
	b.register(getUserErrorResult{errors: errors})
}

// Handle sets the response to invoke a custom handler function. The function
// receives the variables from the incoming request, which match the variables
// registered with ExpectGetUser for a concrete expectation, or any
// variables for a default.
func (b *GetUserExpectation) Handle(fn func(GetUserVariables, http.ResponseWriter)) {
	b.register(getUserRawResult{fn: fn})
}

// ExpectGetUser sets up an expectation for the GetUser operation.
func (s *TestHandler) ExpectGetUser(vars GetUserVariables, opts ...ExpectOption) *GetUserExpectation {
	return &GetUserExpectation{
		handler: s,
		vars:    vars,
		opts:    opts,
	}
}

// DefaultGetUser returns a builder for setting the default response for the
// GetUser operation. The default is used only when no ExpectGetUser
// expectation matches an incoming request. Defaults are infinitely callable
// and never fail at cleanup. Calling DefaultGetUser replaces any previously
// registered default.
func (s *TestHandler) DefaultGetUser() *GetUserExpectation {
	return &GetUserExpectation{
		handler:   s,
		isDefault: true,
	}
}

// ResetGetUser wipes all registered expectations and the default for the
// GetUser operation, and clears any pending cleanup errors. ResetGetUser
// records an error via tb.Errorf and leaves state untouched if the handler
// has already served any request (checked handler-wide, not per-operation),
// so it is safe to call only during test setup. The served-check and the
// clear are performed atomically — no request can mark the handler served
// while a ResetGetUser is in progress.
func (s *TestHandler) ResetGetUser() {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.served {
		s.tb.Errorf("TestHandler.ResetGetUser called after handler has served at least one request")
		return
	}
	s.getUserExpectResponses.clear()
}

// createUserResult is the result interface for the CreateUser operation.
type createUserResult interface {
	writeCreateUserResult(w http.ResponseWriter, vars CreateUserVariables) error
}

type createUserDataResult struct {
	data CreateUserResponse
}

func (r createUserDataResult) writeCreateUserResult(w http.ResponseWriter, _ CreateUserVariables) error {
	return writeGraphQLData(w, r.data)
}

type createUserErrorResult struct {
	errors []GraphQLError
}

func (r createUserErrorResult) writeCreateUserResult(w http.ResponseWriter, _ CreateUserVariables) error {
	return writeGraphQLErrors(w, r.errors)
}

type createUserRawResult struct {
	fn func(CreateUserVariables, http.ResponseWriter)
}

func (r createUserRawResult) writeCreateUserResult(w http.ResponseWriter, vars CreateUserVariables) error {
	r.fn(vars, w)
	return nil
}

// CreateUserExpectation is a builder for setting the response of a CreateUser
// expectation or default. Use ExpectCreateUser or DefaultCreateUser on
// TestHandler to obtain one.
type CreateUserExpectation struct {
	handler   *TestHandler
	vars      CreateUserVariables
	opts      []ExpectOption
	isDefault bool
}

func (b *CreateUserExpectation) register(resp createUserResult) {
	if b.isDefault {
		b.handler.createUserExpectResponses.setDefault(resp)
		return
	}
	b.handler.createUserExpectResponses.expect(b.handler.tb, b.vars, nil, resp, b.opts...)
}

// Respond sets the response data. For an ExpectCreateUser builder this
// registers a concrete expectation; for a DefaultCreateUser builder this
// replaces the per-operation default.
func (b *CreateUserExpectation) Respond(data CreateUserResponse) {
	b.register(createUserDataResult{data: data})
}

// RespondError sets the response to return GraphQL errors. For an
// ExpectCreateUser builder this registers a concrete expectation; for a
// DefaultCreateUser builder this replaces the per-operation default.
func (b *CreateUserExpectation) RespondError(errors ...GraphQLError) {
	b.register(createUserErrorResult{errors: errors})
}

// Handle sets the response to invoke a custom handler function. The function
// receives the variables from the incoming request, which match the variables
// registered with ExpectCreateUser for a concrete expectation, or any
// variables for a default.
func (b *CreateUserExpectation) Handle(fn func(CreateUserVariables, http.ResponseWriter)) {
	b.register(createUserRawResult{fn: fn})
}

// ExpectCreateUser sets up an expectation for the CreateUser operation.
func (s *TestHandler) ExpectCreateUser(vars CreateUserVariables, opts ...ExpectOption) *CreateUserExpectation {
	return &CreateUserExpectation{
		handler: s,
		vars:    vars,
		opts:    opts,
	}
}

// DefaultCreateUser returns a builder for setting the default response for the
// CreateUser operation. The default is used only when no ExpectCreateUser
// expectation matches an incoming request. Defaults are infinitely callable
// and never fail at cleanup. Calling DefaultCreateUser replaces any previously
// registered default.
func (s *TestHandler) DefaultCreateUser() *CreateUserExpectation {
	return &CreateUserExpectation{
		handler:   s,
		isDefault: true,
	}
}

// ResetCreateUser wipes all registered expectations and the default for the
// CreateUser operation, and clears any pending cleanup errors. ResetCreateUser
// records an error via tb.Errorf and leaves state untouched if the handler
// has already served any request (checked handler-wide, not per-operation),
// so it is safe to call only during test setup. The served-check and the
// clear are performed atomically — no request can mark the handler served
// while a ResetCreateUser is in progress.
func (s *TestHandler) ResetCreateUser() {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.served {
		s.tb.Errorf("TestHandler.ResetCreateUser called after handler has served at least one request")
		return
	}
	s.createUserExpectResponses.clear()
}
