// Code generated by github.com/willabides/gqltesthandler/cmd/gqltesthandler. DO NOT EDIT.

package usertest

// GraphQLError represents a GraphQL error in the response.
type GraphQLError struct {
	Message    string         `json:"message"`
	Path       []any          `json:"path,omitempty"`
	Extensions map[string]any `json:"extensions,omitempty"`
}

type CreateUserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

// GetUserVariables contains the variables for the GetUser operation.
type GetUserVariables struct {
	ID string `json:"id"`
}

// GetUserResponse contains the data returned by the GetUser operation.
type GetUserResponse struct {
	User *GetUserResponseUser `json:"user"`
}

type GetUserResponseUser struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

// CreateUserVariables contains the variables for the CreateUser operation.
type CreateUserVariables struct {
	Input CreateUserInput `json:"input"`
}

// CreateUserResponse contains the data returned by the CreateUser operation.
type CreateUserResponse struct {
	CreateUser CreateUserResponseCreateUser `json:"createUser"`
}

type CreateUserResponseCreateUser struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
