// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package client

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type ThreadCommentsFields struct {
	Comments ThreadCommentsFields_Comments "json:\"comments\" graphql:\"comments\""
}

func (t *ThreadCommentsFields) GetComments() *ThreadCommentsFields_Comments {
	if t == nil {
		t = &ThreadCommentsFields{}
	}
	return &t.Comments
}

type PageInfoFields struct {
	EndCursor   *string "json:\"endCursor,omitempty\" graphql:\"endCursor\""
	HasNextPage bool    "json:\"hasNextPage\" graphql:\"hasNextPage\""
}

func (t *PageInfoFields) GetEndCursor() *string {
	if t == nil {
		t = &PageInfoFields{}
	}
	return t.EndCursor
}
func (t *PageInfoFields) GetHasNextPage() bool {
	if t == nil {
		t = &PageInfoFields{}
	}
	return t.HasNextPage
}

type ThreadCommentsFields_Comments_Nodes_Author struct {
	URL string "json:\"url\" graphql:\"url\""
}

func (t *ThreadCommentsFields_Comments_Nodes_Author) GetURL() string {
	if t == nil {
		t = &ThreadCommentsFields_Comments_Nodes_Author{}
	}
	return t.URL
}

type ThreadCommentsFields_Comments_Nodes_Commit struct {
	Oid string "json:\"oid\" graphql:\"oid\""
}

func (t *ThreadCommentsFields_Comments_Nodes_Commit) GetOid() string {
	if t == nil {
		t = &ThreadCommentsFields_Comments_Nodes_Commit{}
	}
	return t.Oid
}

type ThreadCommentsFields_Comments_Nodes_OriginalCommit struct {
	Oid string "json:\"oid\" graphql:\"oid\""
}

func (t *ThreadCommentsFields_Comments_Nodes_OriginalCommit) GetOid() string {
	if t == nil {
		t = &ThreadCommentsFields_Comments_Nodes_OriginalCommit{}
	}
	return t.Oid
}

type ThreadCommentsFields_Comments_Nodes_PullRequestReview struct {
	FullDatabaseID *string "json:\"fullDatabaseId,omitempty\" graphql:\"fullDatabaseId\""
}

func (t *ThreadCommentsFields_Comments_Nodes_PullRequestReview) GetFullDatabaseID() *string {
	if t == nil {
		t = &ThreadCommentsFields_Comments_Nodes_PullRequestReview{}
	}
	return t.FullDatabaseID
}

type ThreadCommentsFields_Comments_Nodes struct {
	Author            *ThreadCommentsFields_Comments_Nodes_Author            "json:\"author,omitempty\" graphql:\"author\""
	Body              string                                                 "json:\"body\" graphql:\"body\""
	Commit            *ThreadCommentsFields_Comments_Nodes_Commit            "json:\"commit,omitempty\" graphql:\"commit\""
	CreatedAt         string                                                 "json:\"createdAt\" graphql:\"createdAt\""
	DiffHunk          string                                                 "json:\"diffHunk\" graphql:\"diffHunk\""
	FullDatabaseID    *string                                                "json:\"fullDatabaseId,omitempty\" graphql:\"fullDatabaseId\""
	OriginalCommit    *ThreadCommentsFields_Comments_Nodes_OriginalCommit    "json:\"originalCommit,omitempty\" graphql:\"originalCommit\""
	PullRequestReview *ThreadCommentsFields_Comments_Nodes_PullRequestReview "json:\"pullRequestReview,omitempty\" graphql:\"pullRequestReview\""
}

func (t *ThreadCommentsFields_Comments_Nodes) GetAuthor() *ThreadCommentsFields_Comments_Nodes_Author {
	if t == nil {
		t = &ThreadCommentsFields_Comments_Nodes{}
	}
	return t.Author
}
func (t *ThreadCommentsFields_Comments_Nodes) GetBody() string {
	if t == nil {
		t = &ThreadCommentsFields_Comments_Nodes{}
	}
	return t.Body
}
func (t *ThreadCommentsFields_Comments_Nodes) GetCommit() *ThreadCommentsFields_Comments_Nodes_Commit {
	if t == nil {
		t = &ThreadCommentsFields_Comments_Nodes{}
	}
	return t.Commit
}
func (t *ThreadCommentsFields_Comments_Nodes) GetCreatedAt() string {
	if t == nil {
		t = &ThreadCommentsFields_Comments_Nodes{}
	}
	return t.CreatedAt
}
func (t *ThreadCommentsFields_Comments_Nodes) GetDiffHunk() string {
	if t == nil {
		t = &ThreadCommentsFields_Comments_Nodes{}
	}
	return t.DiffHunk
}
func (t *ThreadCommentsFields_Comments_Nodes) GetFullDatabaseID() *string {
	if t == nil {
		t = &ThreadCommentsFields_Comments_Nodes{}
	}
	return t.FullDatabaseID
}
func (t *ThreadCommentsFields_Comments_Nodes) GetOriginalCommit() *ThreadCommentsFields_Comments_Nodes_OriginalCommit {
	if t == nil {
		t = &ThreadCommentsFields_Comments_Nodes{}
	}
	return t.OriginalCommit
}
func (t *ThreadCommentsFields_Comments_Nodes) GetPullRequestReview() *ThreadCommentsFields_Comments_Nodes_PullRequestReview {
	if t == nil {
		t = &ThreadCommentsFields_Comments_Nodes{}
	}
	return t.PullRequestReview
}

type ThreadCommentsFields_Comments struct {
	Nodes    []*ThreadCommentsFields_Comments_Nodes "json:\"nodes,omitempty\" graphql:\"nodes\""
	PageInfo *PageInfoFields                        "json:\"pageInfo\" graphql:\"pageInfo\""
}

func (t *ThreadCommentsFields_Comments) GetNodes() []*ThreadCommentsFields_Comments_Nodes {
	if t == nil {
		t = &ThreadCommentsFields_Comments{}
	}
	return t.Nodes
}
func (t *ThreadCommentsFields_Comments) GetPageInfo() *PageInfoFields {
	if t == nil {
		t = &ThreadCommentsFields_Comments{}
	}
	return t.PageInfo
}

type GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes_Author struct {
	URL string "json:\"url\" graphql:\"url\""
}

func (t *GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes_Author) GetURL() string {
	if t == nil {
		t = &GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes_Author{}
	}
	return t.URL
}

type GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes_Commit struct {
	Oid string "json:\"oid\" graphql:\"oid\""
}

func (t *GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes_Commit) GetOid() string {
	if t == nil {
		t = &GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes_Commit{}
	}
	return t.Oid
}

type GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes struct {
	Author         *GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes_Author "json:\"author,omitempty\" graphql:\"author\""
	Body           string                                                             "json:\"body\" graphql:\"body\""
	Commit         *GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes_Commit "json:\"commit,omitempty\" graphql:\"commit\""
	CreatedAt      string                                                             "json:\"createdAt\" graphql:\"createdAt\""
	FullDatabaseID *string                                                            "json:\"fullDatabaseId,omitempty\" graphql:\"fullDatabaseId\""
	State          PullRequestReviewState                                             "json:\"state\" graphql:\"state\""
	SubmittedAt    *string                                                            "json:\"submittedAt,omitempty\" graphql:\"submittedAt\""
	URL            string                                                             "json:\"url\" graphql:\"url\""
}

func (t *GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes) GetAuthor() *GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes_Author {
	if t == nil {
		t = &GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes{}
	}
	return t.Author
}
func (t *GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes) GetBody() string {
	if t == nil {
		t = &GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes{}
	}
	return t.Body
}
func (t *GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes) GetCommit() *GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes_Commit {
	if t == nil {
		t = &GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes{}
	}
	return t.Commit
}
func (t *GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes) GetCreatedAt() string {
	if t == nil {
		t = &GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes{}
	}
	return t.CreatedAt
}
func (t *GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes) GetFullDatabaseID() *string {
	if t == nil {
		t = &GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes{}
	}
	return t.FullDatabaseID
}
func (t *GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes) GetState() *PullRequestReviewState {
	if t == nil {
		t = &GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes{}
	}
	return &t.State
}
func (t *GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes) GetSubmittedAt() *string {
	if t == nil {
		t = &GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes{}
	}
	return t.SubmittedAt
}
func (t *GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes) GetURL() string {
	if t == nil {
		t = &GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes{}
	}
	return t.URL
}

type GetPullRequestReviews_Repository_PullRequest_Reviews struct {
	Nodes    []*GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes "json:\"nodes,omitempty\" graphql:\"nodes\""
	PageInfo *PageInfoFields                                               "json:\"pageInfo\" graphql:\"pageInfo\""
}

func (t *GetPullRequestReviews_Repository_PullRequest_Reviews) GetNodes() []*GetPullRequestReviews_Repository_PullRequest_Reviews_Nodes {
	if t == nil {
		t = &GetPullRequestReviews_Repository_PullRequest_Reviews{}
	}
	return t.Nodes
}
func (t *GetPullRequestReviews_Repository_PullRequest_Reviews) GetPageInfo() *PageInfoFields {
	if t == nil {
		t = &GetPullRequestReviews_Repository_PullRequest_Reviews{}
	}
	return t.PageInfo
}

type GetPullRequestReviews_Repository_PullRequest struct {
	Reviews *GetPullRequestReviews_Repository_PullRequest_Reviews "json:\"reviews,omitempty\" graphql:\"reviews\""
	URL     string                                                "json:\"url\" graphql:\"url\""
}

func (t *GetPullRequestReviews_Repository_PullRequest) GetReviews() *GetPullRequestReviews_Repository_PullRequest_Reviews {
	if t == nil {
		t = &GetPullRequestReviews_Repository_PullRequest{}
	}
	return t.Reviews
}
func (t *GetPullRequestReviews_Repository_PullRequest) GetURL() string {
	if t == nil {
		t = &GetPullRequestReviews_Repository_PullRequest{}
	}
	return t.URL
}

type GetPullRequestReviews_Repository struct {
	PullRequest *GetPullRequestReviews_Repository_PullRequest "json:\"pullRequest,omitempty\" graphql:\"pullRequest\""
}

func (t *GetPullRequestReviews_Repository) GetPullRequest() *GetPullRequestReviews_Repository_PullRequest {
	if t == nil {
		t = &GetPullRequestReviews_Repository{}
	}
	return t.PullRequest
}

type GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ResolvedBy struct {
	URL string "json:\"url\" graphql:\"url\""
}

func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ResolvedBy) GetURL() string {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ResolvedBy{}
	}
	return t.URL
}

type GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_Author struct {
	URL string "json:\"url\" graphql:\"url\""
}

func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_Author) GetURL() string {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_Author{}
	}
	return t.URL
}

type GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_Commit struct {
	Oid string "json:\"oid\" graphql:\"oid\""
}

func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_Commit) GetOid() string {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_Commit{}
	}
	return t.Oid
}

type GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_OriginalCommit struct {
	Oid string "json:\"oid\" graphql:\"oid\""
}

func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_OriginalCommit) GetOid() string {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_OriginalCommit{}
	}
	return t.Oid
}

type GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_PullRequestReview struct {
	FullDatabaseID *string "json:\"fullDatabaseId,omitempty\" graphql:\"fullDatabaseId\""
}

func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_PullRequestReview) GetFullDatabaseID() *string {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_PullRequestReview{}
	}
	return t.FullDatabaseID
}

type GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes struct {
	Author            *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_Author            "json:\"author,omitempty\" graphql:\"author\""
	Body              string                                                                                                                  "json:\"body\" graphql:\"body\""
	Commit            *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_Commit            "json:\"commit,omitempty\" graphql:\"commit\""
	CreatedAt         string                                                                                                                  "json:\"createdAt\" graphql:\"createdAt\""
	DiffHunk          string                                                                                                                  "json:\"diffHunk\" graphql:\"diffHunk\""
	FullDatabaseID    *string                                                                                                                 "json:\"fullDatabaseId,omitempty\" graphql:\"fullDatabaseId\""
	OriginalCommit    *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_OriginalCommit    "json:\"originalCommit,omitempty\" graphql:\"originalCommit\""
	PullRequestReview *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_PullRequestReview "json:\"pullRequestReview,omitempty\" graphql:\"pullRequestReview\""
}

func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes) GetAuthor() *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_Author {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes{}
	}
	return t.Author
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes) GetBody() string {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes{}
	}
	return t.Body
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes) GetCommit() *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_Commit {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes{}
	}
	return t.Commit
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes) GetCreatedAt() string {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes{}
	}
	return t.CreatedAt
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes) GetDiffHunk() string {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes{}
	}
	return t.DiffHunk
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes) GetFullDatabaseID() *string {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes{}
	}
	return t.FullDatabaseID
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes) GetOriginalCommit() *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_OriginalCommit {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes{}
	}
	return t.OriginalCommit
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes) GetPullRequestReview() *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes_PullRequestReview {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes{}
	}
	return t.PullRequestReview
}

type GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments struct {
	Nodes    []*GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes "json:\"nodes,omitempty\" graphql:\"nodes\""
	PageInfo *PageInfoFields                                                                                         "json:\"pageInfo\" graphql:\"pageInfo\""
}

func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments) GetNodes() []*GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments_Nodes {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments{}
	}
	return t.Nodes
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments) GetPageInfo() *PageInfoFields {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments{}
	}
	return t.PageInfo
}

type GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes struct {
	Comments          GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments "json:\"comments\" graphql:\"comments\""
	DiffSide          DiffSide                                                                                       "json:\"diffSide\" graphql:\"diffSide\""
	ID                string                                                                                         "json:\"id\" graphql:\"id\""
	IsOutdated        bool                                                                                           "json:\"isOutdated\" graphql:\"isOutdated\""
	IsResolved        bool                                                                                           "json:\"isResolved\" graphql:\"isResolved\""
	Line              *int                                                                                           "json:\"line,omitempty\" graphql:\"line\""
	OriginalLine      *int                                                                                           "json:\"originalLine,omitempty\" graphql:\"originalLine\""
	OriginalStartLine *int                                                                                           "json:\"originalStartLine,omitempty\" graphql:\"originalStartLine\""
	Path              string                                                                                         "json:\"path\" graphql:\"path\""
	ResolvedBy        *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ResolvedBy                   "json:\"resolvedBy,omitempty\" graphql:\"resolvedBy\""
	StartDiffSide     *DiffSide                                                                                      "json:\"startDiffSide,omitempty\" graphql:\"startDiffSide\""
	StartLine         *int                                                                                           "json:\"startLine,omitempty\" graphql:\"startLine\""
	SubjectType       PullRequestReviewThreadSubjectType                                                             "json:\"subjectType\" graphql:\"subjectType\""
}

func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes) GetComments() *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ThreadCommentsFields_Comments {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes{}
	}
	return &t.Comments
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes) GetDiffSide() *DiffSide {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes{}
	}
	return &t.DiffSide
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes) GetID() string {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes{}
	}
	return t.ID
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes) GetIsOutdated() bool {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes{}
	}
	return t.IsOutdated
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes) GetIsResolved() bool {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes{}
	}
	return t.IsResolved
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes) GetLine() *int {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes{}
	}
	return t.Line
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes) GetOriginalLine() *int {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes{}
	}
	return t.OriginalLine
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes) GetOriginalStartLine() *int {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes{}
	}
	return t.OriginalStartLine
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes) GetPath() string {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes{}
	}
	return t.Path
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes) GetResolvedBy() *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes_ResolvedBy {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes{}
	}
	return t.ResolvedBy
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes) GetStartDiffSide() *DiffSide {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes{}
	}
	return t.StartDiffSide
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes) GetStartLine() *int {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes{}
	}
	return t.StartLine
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes) GetSubjectType() *PullRequestReviewThreadSubjectType {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes{}
	}
	return &t.SubjectType
}

type GetPullRequestThreads_Repository_PullRequest_ReviewThreads struct {
	Nodes    []*GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes "json:\"nodes,omitempty\" graphql:\"nodes\""
	PageInfo *PageInfoFields                                                     "json:\"pageInfo\" graphql:\"pageInfo\""
}

func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads) GetNodes() []*GetPullRequestThreads_Repository_PullRequest_ReviewThreads_Nodes {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads{}
	}
	return t.Nodes
}
func (t *GetPullRequestThreads_Repository_PullRequest_ReviewThreads) GetPageInfo() *PageInfoFields {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest_ReviewThreads{}
	}
	return t.PageInfo
}

type GetPullRequestThreads_Repository_PullRequest struct {
	ReviewThreads GetPullRequestThreads_Repository_PullRequest_ReviewThreads "json:\"reviewThreads\" graphql:\"reviewThreads\""
}

func (t *GetPullRequestThreads_Repository_PullRequest) GetReviewThreads() *GetPullRequestThreads_Repository_PullRequest_ReviewThreads {
	if t == nil {
		t = &GetPullRequestThreads_Repository_PullRequest{}
	}
	return &t.ReviewThreads
}

type GetPullRequestThreads_Repository struct {
	PullRequest *GetPullRequestThreads_Repository_PullRequest "json:\"pullRequest,omitempty\" graphql:\"pullRequest\""
}

func (t *GetPullRequestThreads_Repository) GetPullRequest() *GetPullRequestThreads_Repository_PullRequest {
	if t == nil {
		t = &GetPullRequestThreads_Repository{}
	}
	return t.PullRequest
}

type GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_Author struct {
	URL string "json:\"url\" graphql:\"url\""
}

func (t *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_Author) GetURL() string {
	if t == nil {
		t = &GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_Author{}
	}
	return t.URL
}

type GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_Commit struct {
	Oid string "json:\"oid\" graphql:\"oid\""
}

func (t *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_Commit) GetOid() string {
	if t == nil {
		t = &GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_Commit{}
	}
	return t.Oid
}

type GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_OriginalCommit struct {
	Oid string "json:\"oid\" graphql:\"oid\""
}

func (t *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_OriginalCommit) GetOid() string {
	if t == nil {
		t = &GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_OriginalCommit{}
	}
	return t.Oid
}

type GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_PullRequestReview struct {
	FullDatabaseID *string "json:\"fullDatabaseId,omitempty\" graphql:\"fullDatabaseId\""
}

func (t *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_PullRequestReview) GetFullDatabaseID() *string {
	if t == nil {
		t = &GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_PullRequestReview{}
	}
	return t.FullDatabaseID
}

type GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes struct {
	Author            *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_Author            "json:\"author,omitempty\" graphql:\"author\""
	Body              string                                                                                   "json:\"body\" graphql:\"body\""
	Commit            *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_Commit            "json:\"commit,omitempty\" graphql:\"commit\""
	CreatedAt         string                                                                                   "json:\"createdAt\" graphql:\"createdAt\""
	DiffHunk          string                                                                                   "json:\"diffHunk\" graphql:\"diffHunk\""
	FullDatabaseID    *string                                                                                  "json:\"fullDatabaseId,omitempty\" graphql:\"fullDatabaseId\""
	OriginalCommit    *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_OriginalCommit    "json:\"originalCommit,omitempty\" graphql:\"originalCommit\""
	PullRequestReview *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_PullRequestReview "json:\"pullRequestReview,omitempty\" graphql:\"pullRequestReview\""
}

func (t *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes) GetAuthor() *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_Author {
	if t == nil {
		t = &GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes{}
	}
	return t.Author
}
func (t *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes) GetBody() string {
	if t == nil {
		t = &GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes{}
	}
	return t.Body
}
func (t *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes) GetCommit() *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_Commit {
	if t == nil {
		t = &GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes{}
	}
	return t.Commit
}
func (t *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes) GetCreatedAt() string {
	if t == nil {
		t = &GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes{}
	}
	return t.CreatedAt
}
func (t *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes) GetDiffHunk() string {
	if t == nil {
		t = &GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes{}
	}
	return t.DiffHunk
}
func (t *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes) GetFullDatabaseID() *string {
	if t == nil {
		t = &GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes{}
	}
	return t.FullDatabaseID
}
func (t *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes) GetOriginalCommit() *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_OriginalCommit {
	if t == nil {
		t = &GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes{}
	}
	return t.OriginalCommit
}
func (t *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes) GetPullRequestReview() *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes_PullRequestReview {
	if t == nil {
		t = &GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes{}
	}
	return t.PullRequestReview
}

type GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments struct {
	Nodes    []*GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes "json:\"nodes,omitempty\" graphql:\"nodes\""
	PageInfo *PageInfoFields                                                          "json:\"pageInfo\" graphql:\"pageInfo\""
}

func (t *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments) GetNodes() []*GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments_Nodes {
	if t == nil {
		t = &GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments{}
	}
	return t.Nodes
}
func (t *GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments) GetPageInfo() *PageInfoFields {
	if t == nil {
		t = &GetPullRequestThreadComments_Node_ThreadCommentsFields_Comments{}
	}
	return t.PageInfo
}

type GetPullRequestReviews struct {
	Repository *GetPullRequestReviews_Repository "json:\"repository,omitempty\" graphql:\"repository\""
}

func (t *GetPullRequestReviews) GetRepository() *GetPullRequestReviews_Repository {
	if t == nil {
		t = &GetPullRequestReviews{}
	}
	return t.Repository
}

type GetPullRequestThreads struct {
	Repository *GetPullRequestThreads_Repository "json:\"repository,omitempty\" graphql:\"repository\""
}

func (t *GetPullRequestThreads) GetRepository() *GetPullRequestThreads_Repository {
	if t == nil {
		t = &GetPullRequestThreads{}
	}
	return t.Repository
}

type GetPullRequestThreadComments struct {
	Node *ThreadCommentsFields "json:\"node,omitempty\" graphql:\"node\""
}

func (t *GetPullRequestThreadComments) GetNode() *ThreadCommentsFields {
	if t == nil {
		t = &GetPullRequestThreadComments{}
	}
	return t.Node
}

const GetPullRequestReviewsDocument = `query GetPullRequestReviews ($owner: String!, $repo: String!, $pullNumber: Int!, $cursor: String) {
	repository(owner: $owner, name: $repo) {
		pullRequest(number: $pullNumber) {
			url
			reviews(first: 100, after: $cursor) {
				nodes {
					url
					fullDatabaseId
					author {
						url
					}
					body
					state
					createdAt
					submittedAt
					commit {
						oid
					}
				}
				pageInfo {
					... PageInfoFields
				}
			}
		}
	}
}
fragment PageInfoFields on PageInfo {
	endCursor
	hasNextPage
}
`

func (c *Client) GetPullRequestReviews(ctx context.Context, owner string, repo string, pullNumber int, cursor *string, interceptors ...clientv2.RequestInterceptor) (*GetPullRequestReviews, error) {
	vars := map[string]any{
		"owner":      owner,
		"repo":       repo,
		"pullNumber": pullNumber,
		"cursor":     cursor,
	}

	var res GetPullRequestReviews
	if err := c.Client.Post(ctx, "GetPullRequestReviews", GetPullRequestReviewsDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetPullRequestThreadsDocument = `query GetPullRequestThreads ($owner: String!, $repo: String!, $pullNumber: Int!, $threadsCursor: String, $commentsCursor: String) {
	repository(owner: $owner, name: $repo) {
		pullRequest(number: $pullNumber) {
			reviewThreads(first: 100, after: $threadsCursor) {
				nodes {
					id
					isResolved
					isOutdated
					resolvedBy {
						url
					}
					path
					line
					startLine
					originalLine
					originalStartLine
					diffSide
					startDiffSide
					subjectType
					... ThreadCommentsFields
				}
				pageInfo {
					... PageInfoFields
				}
			}
		}
	}
}
fragment ThreadCommentsFields on PullRequestReviewThread {
	comments(first: 100, after: $commentsCursor) {
		nodes {
			fullDatabaseId
			author {
				url
			}
			body
			createdAt
			diffHunk
			commit {
				oid
			}
			originalCommit {
				oid
			}
			pullRequestReview {
				fullDatabaseId
			}
		}
		pageInfo {
			... PageInfoFields
		}
	}
}
fragment PageInfoFields on PageInfo {
	endCursor
	hasNextPage
}
`

func (c *Client) GetPullRequestThreads(ctx context.Context, owner string, repo string, pullNumber int, threadsCursor *string, commentsCursor *string, interceptors ...clientv2.RequestInterceptor) (*GetPullRequestThreads, error) {
	vars := map[string]any{
		"owner":          owner,
		"repo":           repo,
		"pullNumber":     pullNumber,
		"threadsCursor":  threadsCursor,
		"commentsCursor": commentsCursor,
	}

	var res GetPullRequestThreads
	if err := c.Client.Post(ctx, "GetPullRequestThreads", GetPullRequestThreadsDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetPullRequestThreadCommentsDocument = `query GetPullRequestThreadComments ($threadID: ID!, $commentsCursor: String) {
	node(id: $threadID) {
		... ThreadCommentsFields
	}
}
fragment ThreadCommentsFields on PullRequestReviewThread {
	comments(first: 100, after: $commentsCursor) {
		nodes {
			fullDatabaseId
			author {
				url
			}
			body
			createdAt
			diffHunk
			commit {
				oid
			}
			originalCommit {
				oid
			}
			pullRequestReview {
				fullDatabaseId
			}
		}
		pageInfo {
			... PageInfoFields
		}
	}
}
fragment PageInfoFields on PageInfo {
	endCursor
	hasNextPage
}
`

func (c *Client) GetPullRequestThreadComments(ctx context.Context, threadID string, commentsCursor *string, interceptors ...clientv2.RequestInterceptor) (*GetPullRequestThreadComments, error) {
	vars := map[string]any{
		"threadID":       threadID,
		"commentsCursor": commentsCursor,
	}

	var res GetPullRequestThreadComments
	if err := c.Client.Post(ctx, "GetPullRequestThreadComments", GetPullRequestThreadCommentsDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetPullRequestReviewsDocument:        "GetPullRequestReviews",
	GetPullRequestThreadsDocument:        "GetPullRequestThreads",
	GetPullRequestThreadCommentsDocument: "GetPullRequestThreadComments",
}
