// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package userapi

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// CreateUserCreateUser includes the requested fields of the GraphQL type User.
type CreateUserCreateUser struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

// GetId returns CreateUserCreateUser.Id, and is useful for accessing the field via an interface.
func (v *CreateUserCreateUser) GetId() string { return v.Id }

// GetName returns CreateUserCreateUser.Name, and is useful for accessing the field via an interface.
func (v *CreateUserCreateUser) GetName() string { return v.Name }

// GetEmail returns CreateUserCreateUser.Email, and is useful for accessing the field via an interface.
func (v *CreateUserCreateUser) GetEmail() string { return v.Email }

type CreateUserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

// GetName returns CreateUserInput.Name, and is useful for accessing the field via an interface.
func (v *CreateUserInput) GetName() string { return v.Name }

// GetEmail returns CreateUserInput.Email, and is useful for accessing the field via an interface.
func (v *CreateUserInput) GetEmail() string { return v.Email }

// CreateUserResponse is returned by CreateUser on success.
type CreateUserResponse struct {
	CreateUser CreateUserCreateUser `json:"createUser"`
}

// GetCreateUser returns CreateUserResponse.CreateUser, and is useful for accessing the field via an interface.
func (v *CreateUserResponse) GetCreateUser() CreateUserCreateUser { return v.CreateUser }

// GetUserResponse is returned by GetUser on success.
type GetUserResponse struct {
	User GetUserUser `json:"user"`
}

// GetUser returns GetUserResponse.User, and is useful for accessing the field via an interface.
func (v *GetUserResponse) GetUser() GetUserUser { return v.User }

// GetUserUser includes the requested fields of the GraphQL type User.
type GetUserUser struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

// GetId returns GetUserUser.Id, and is useful for accessing the field via an interface.
func (v *GetUserUser) GetId() string { return v.Id }

// GetName returns GetUserUser.Name, and is useful for accessing the field via an interface.
func (v *GetUserUser) GetName() string { return v.Name }

// GetEmail returns GetUserUser.Email, and is useful for accessing the field via an interface.
func (v *GetUserUser) GetEmail() string { return v.Email }

// __CreateUserInput is used internally by genqlient
type __CreateUserInput struct {
	Input CreateUserInput `json:"input"`
}

// GetInput returns __CreateUserInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateUserInput) GetInput() CreateUserInput { return v.Input }

// __GetUserInput is used internally by genqlient
type __GetUserInput struct {
	Id string `json:"id"`
}

// GetId returns __GetUserInput.Id, and is useful for accessing the field via an interface.
func (v *__GetUserInput) GetId() string { return v.Id }

// The mutation executed by CreateUser.
const CreateUser_Operation = `
mutation CreateUser ($input: CreateUserInput!) {
	createUser(input: $input) {
		id
		name
		email
	}
}
`

func CreateUser(
	ctx_ context.Context,
	client_ graphql.Client,
	input CreateUserInput,
) (data_ *CreateUserResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateUser",
		Query:  CreateUser_Operation,
		Variables: &__CreateUserInput{
			Input: input,
		},
	}

	data_ = &CreateUserResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetUser.
const GetUser_Operation = `
query GetUser ($id: ID!) {
	user(id: $id) {
		id
		name
		email
	}
}
`

func GetUser(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *GetUserResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetUser",
		Query:  GetUser_Operation,
		Variables: &__GetUserInput{
			Id: id,
		},
	}

	data_ = &GetUserResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
