// Code generated by github.com/willabides/gqltesthandler/cmd/gqltesthandler. DO NOT EDIT.

package ghtest

import (
	"net/http"
	"sync"
)

// TestHandler is a mock GraphQL HTTP handler for testing.
// Set expectations with Expect methods, then use as an http.Handler.
type TestHandler struct {
	tb      TB
	handler http.Handler

	mu     sync.Mutex
	served bool

	getPullRequestReviewsExpectResponses        expectResponses[GetPullRequestReviewsVariables, getPullRequestReviewsResult]
	getPullRequestThreadsExpectResponses        expectResponses[GetPullRequestThreadsVariables, getPullRequestThreadsResult]
	getPullRequestThreadCommentsExpectResponses expectResponses[GetPullRequestThreadCommentsVariables, getPullRequestThreadCommentsResult]
}

func (s *TestHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	s.handler.ServeHTTP(w, r)
}

// NewTestHandler creates a new TestHandler for use in tests.
func NewTestHandler(tb TB) *TestHandler {
	th := &TestHandler{tb: tb}
	th.handler = &testServer{tb: tb, handler: th}
	return th
}

// markServed records that the handler has processed a request. Once true,
// Reset and Reset<OpName> refuse to wipe state.
func (s *TestHandler) markServed() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.served = true
}

// Reset wipes all registered expectations and defaults on this handler and
// clears any pending cleanup errors so previously-unmet expectations will not
// fail the test. Reset records an error via tb.Errorf and leaves state
// untouched if the handler has already served any request (checked
// handler-wide, not per-operation), so it is safe to call only during test
// setup. The served-check and the clear are performed atomically — no
// request can mark the handler served while a Reset is in progress.
func (s *TestHandler) Reset() {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.served {
		s.tb.Errorf("TestHandler.Reset called after handler has served at least one request")
		return
	}
	s.getPullRequestReviewsExpectResponses.clear()
	s.getPullRequestThreadsExpectResponses.clear()
	s.getPullRequestThreadCommentsExpectResponses.clear()
}

// getPullRequestReviewsResult is the result interface for the GetPullRequestReviews operation.
type getPullRequestReviewsResult interface {
	writeGetPullRequestReviewsResult(w http.ResponseWriter, vars GetPullRequestReviewsVariables) error
}

type getPullRequestReviewsDataResult struct {
	data GetPullRequestReviewsResponse
}

func (r getPullRequestReviewsDataResult) writeGetPullRequestReviewsResult(w http.ResponseWriter, _ GetPullRequestReviewsVariables) error {
	return writeGraphQLData(w, r.data)
}

type getPullRequestReviewsErrorResult struct {
	errors []GraphQLError
}

func (r getPullRequestReviewsErrorResult) writeGetPullRequestReviewsResult(w http.ResponseWriter, _ GetPullRequestReviewsVariables) error {
	return writeGraphQLErrors(w, r.errors)
}

type getPullRequestReviewsRawResult struct {
	fn func(GetPullRequestReviewsVariables, http.ResponseWriter)
}

func (r getPullRequestReviewsRawResult) writeGetPullRequestReviewsResult(w http.ResponseWriter, vars GetPullRequestReviewsVariables) error {
	r.fn(vars, w)
	return nil
}

// GetPullRequestReviewsExpectation is a builder for setting the response of a GetPullRequestReviews
// expectation or default. Use ExpectGetPullRequestReviews or DefaultGetPullRequestReviews on
// TestHandler to obtain one.
type GetPullRequestReviewsExpectation struct {
	handler   *TestHandler
	vars      GetPullRequestReviewsVariables
	opts      []ExpectOption
	isDefault bool
}

func (b *GetPullRequestReviewsExpectation) register(resp getPullRequestReviewsResult) {
	if b.isDefault {
		b.handler.getPullRequestReviewsExpectResponses.setDefault(resp)
		return
	}
	b.handler.getPullRequestReviewsExpectResponses.expect(b.handler.tb, b.vars, nil, resp, b.opts...)
}

// Respond sets the response data. For an ExpectGetPullRequestReviews builder this
// registers a concrete expectation; for a DefaultGetPullRequestReviews builder this
// replaces the per-operation default.
func (b *GetPullRequestReviewsExpectation) Respond(data GetPullRequestReviewsResponse) {
	b.register(getPullRequestReviewsDataResult{data: data})
}

// RespondError sets the response to return GraphQL errors. For an
// ExpectGetPullRequestReviews builder this registers a concrete expectation; for a
// DefaultGetPullRequestReviews builder this replaces the per-operation default.
func (b *GetPullRequestReviewsExpectation) RespondError(errors ...GraphQLError) {
	b.register(getPullRequestReviewsErrorResult{errors: errors})
}

// Handle sets the response to invoke a custom handler function. The function
// receives the variables from the incoming request, which match the variables
// registered with ExpectGetPullRequestReviews for a concrete expectation, or any
// variables for a default.
func (b *GetPullRequestReviewsExpectation) Handle(fn func(GetPullRequestReviewsVariables, http.ResponseWriter)) {
	b.register(getPullRequestReviewsRawResult{fn: fn})
}

// ExpectGetPullRequestReviews sets up an expectation for the GetPullRequestReviews operation.
func (s *TestHandler) ExpectGetPullRequestReviews(vars GetPullRequestReviewsVariables, opts ...ExpectOption) *GetPullRequestReviewsExpectation {
	return &GetPullRequestReviewsExpectation{
		handler: s,
		vars:    vars,
		opts:    opts,
	}
}

// DefaultGetPullRequestReviews returns a builder for setting the default response for the
// GetPullRequestReviews operation. The default is used only when no ExpectGetPullRequestReviews
// expectation matches an incoming request. Defaults are infinitely callable
// and never fail at cleanup. Calling DefaultGetPullRequestReviews replaces any previously
// registered default.
func (s *TestHandler) DefaultGetPullRequestReviews() *GetPullRequestReviewsExpectation {
	return &GetPullRequestReviewsExpectation{
		handler:   s,
		isDefault: true,
	}
}

// ResetGetPullRequestReviews wipes all registered expectations and the default for the
// GetPullRequestReviews operation, and clears any pending cleanup errors. ResetGetPullRequestReviews
// records an error via tb.Errorf and leaves state untouched if the handler
// has already served any request (checked handler-wide, not per-operation),
// so it is safe to call only during test setup. The served-check and the
// clear are performed atomically — no request can mark the handler served
// while a ResetGetPullRequestReviews is in progress.
func (s *TestHandler) ResetGetPullRequestReviews() {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.served {
		s.tb.Errorf("TestHandler.ResetGetPullRequestReviews called after handler has served at least one request")
		return
	}
	s.getPullRequestReviewsExpectResponses.clear()
}

// getPullRequestThreadsResult is the result interface for the GetPullRequestThreads operation.
type getPullRequestThreadsResult interface {
	writeGetPullRequestThreadsResult(w http.ResponseWriter, vars GetPullRequestThreadsVariables) error
}

type getPullRequestThreadsDataResult struct {
	data GetPullRequestThreadsResponse
}

func (r getPullRequestThreadsDataResult) writeGetPullRequestThreadsResult(w http.ResponseWriter, _ GetPullRequestThreadsVariables) error {
	return writeGraphQLData(w, r.data)
}

type getPullRequestThreadsErrorResult struct {
	errors []GraphQLError
}

func (r getPullRequestThreadsErrorResult) writeGetPullRequestThreadsResult(w http.ResponseWriter, _ GetPullRequestThreadsVariables) error {
	return writeGraphQLErrors(w, r.errors)
}

type getPullRequestThreadsRawResult struct {
	fn func(GetPullRequestThreadsVariables, http.ResponseWriter)
}

func (r getPullRequestThreadsRawResult) writeGetPullRequestThreadsResult(w http.ResponseWriter, vars GetPullRequestThreadsVariables) error {
	r.fn(vars, w)
	return nil
}

// GetPullRequestThreadsExpectation is a builder for setting the response of a GetPullRequestThreads
// expectation or default. Use ExpectGetPullRequestThreads or DefaultGetPullRequestThreads on
// TestHandler to obtain one.
type GetPullRequestThreadsExpectation struct {
	handler   *TestHandler
	vars      GetPullRequestThreadsVariables
	opts      []ExpectOption
	isDefault bool
}

func (b *GetPullRequestThreadsExpectation) register(resp getPullRequestThreadsResult) {
	if b.isDefault {
		b.handler.getPullRequestThreadsExpectResponses.setDefault(resp)
		return
	}
	b.handler.getPullRequestThreadsExpectResponses.expect(b.handler.tb, b.vars, nil, resp, b.opts...)
}

// Respond sets the response data. For an ExpectGetPullRequestThreads builder this
// registers a concrete expectation; for a DefaultGetPullRequestThreads builder this
// replaces the per-operation default.
func (b *GetPullRequestThreadsExpectation) Respond(data GetPullRequestThreadsResponse) {
	b.register(getPullRequestThreadsDataResult{data: data})
}

// RespondError sets the response to return GraphQL errors. For an
// ExpectGetPullRequestThreads builder this registers a concrete expectation; for a
// DefaultGetPullRequestThreads builder this replaces the per-operation default.
func (b *GetPullRequestThreadsExpectation) RespondError(errors ...GraphQLError) {
	b.register(getPullRequestThreadsErrorResult{errors: errors})
}

// Handle sets the response to invoke a custom handler function. The function
// receives the variables from the incoming request, which match the variables
// registered with ExpectGetPullRequestThreads for a concrete expectation, or any
// variables for a default.
func (b *GetPullRequestThreadsExpectation) Handle(fn func(GetPullRequestThreadsVariables, http.ResponseWriter)) {
	b.register(getPullRequestThreadsRawResult{fn: fn})
}

// ExpectGetPullRequestThreads sets up an expectation for the GetPullRequestThreads operation.
func (s *TestHandler) ExpectGetPullRequestThreads(vars GetPullRequestThreadsVariables, opts ...ExpectOption) *GetPullRequestThreadsExpectation {
	return &GetPullRequestThreadsExpectation{
		handler: s,
		vars:    vars,
		opts:    opts,
	}
}

// DefaultGetPullRequestThreads returns a builder for setting the default response for the
// GetPullRequestThreads operation. The default is used only when no ExpectGetPullRequestThreads
// expectation matches an incoming request. Defaults are infinitely callable
// and never fail at cleanup. Calling DefaultGetPullRequestThreads replaces any previously
// registered default.
func (s *TestHandler) DefaultGetPullRequestThreads() *GetPullRequestThreadsExpectation {
	return &GetPullRequestThreadsExpectation{
		handler:   s,
		isDefault: true,
	}
}

// ResetGetPullRequestThreads wipes all registered expectations and the default for the
// GetPullRequestThreads operation, and clears any pending cleanup errors. ResetGetPullRequestThreads
// records an error via tb.Errorf and leaves state untouched if the handler
// has already served any request (checked handler-wide, not per-operation),
// so it is safe to call only during test setup. The served-check and the
// clear are performed atomically — no request can mark the handler served
// while a ResetGetPullRequestThreads is in progress.
func (s *TestHandler) ResetGetPullRequestThreads() {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.served {
		s.tb.Errorf("TestHandler.ResetGetPullRequestThreads called after handler has served at least one request")
		return
	}
	s.getPullRequestThreadsExpectResponses.clear()
}

// getPullRequestThreadCommentsResult is the result interface for the GetPullRequestThreadComments operation.
type getPullRequestThreadCommentsResult interface {
	writeGetPullRequestThreadCommentsResult(w http.ResponseWriter, vars GetPullRequestThreadCommentsVariables) error
}

type getPullRequestThreadCommentsDataResult struct {
	data GetPullRequestThreadCommentsResponse
}

func (r getPullRequestThreadCommentsDataResult) writeGetPullRequestThreadCommentsResult(w http.ResponseWriter, _ GetPullRequestThreadCommentsVariables) error {
	return writeGraphQLData(w, r.data)
}

type getPullRequestThreadCommentsErrorResult struct {
	errors []GraphQLError
}

func (r getPullRequestThreadCommentsErrorResult) writeGetPullRequestThreadCommentsResult(w http.ResponseWriter, _ GetPullRequestThreadCommentsVariables) error {
	return writeGraphQLErrors(w, r.errors)
}

type getPullRequestThreadCommentsRawResult struct {
	fn func(GetPullRequestThreadCommentsVariables, http.ResponseWriter)
}

func (r getPullRequestThreadCommentsRawResult) writeGetPullRequestThreadCommentsResult(w http.ResponseWriter, vars GetPullRequestThreadCommentsVariables) error {
	r.fn(vars, w)
	return nil
}

// GetPullRequestThreadCommentsExpectation is a builder for setting the response of a GetPullRequestThreadComments
// expectation or default. Use ExpectGetPullRequestThreadComments or DefaultGetPullRequestThreadComments on
// TestHandler to obtain one.
type GetPullRequestThreadCommentsExpectation struct {
	handler   *TestHandler
	vars      GetPullRequestThreadCommentsVariables
	opts      []ExpectOption
	isDefault bool
}

func (b *GetPullRequestThreadCommentsExpectation) register(resp getPullRequestThreadCommentsResult) {
	if b.isDefault {
		b.handler.getPullRequestThreadCommentsExpectResponses.setDefault(resp)
		return
	}
	b.handler.getPullRequestThreadCommentsExpectResponses.expect(b.handler.tb, b.vars, nil, resp, b.opts...)
}

// Respond sets the response data. For an ExpectGetPullRequestThreadComments builder this
// registers a concrete expectation; for a DefaultGetPullRequestThreadComments builder this
// replaces the per-operation default.
func (b *GetPullRequestThreadCommentsExpectation) Respond(data GetPullRequestThreadCommentsResponse) {
	b.register(getPullRequestThreadCommentsDataResult{data: data})
}

// RespondError sets the response to return GraphQL errors. For an
// ExpectGetPullRequestThreadComments builder this registers a concrete expectation; for a
// DefaultGetPullRequestThreadComments builder this replaces the per-operation default.
func (b *GetPullRequestThreadCommentsExpectation) RespondError(errors ...GraphQLError) {
	b.register(getPullRequestThreadCommentsErrorResult{errors: errors})
}

// Handle sets the response to invoke a custom handler function. The function
// receives the variables from the incoming request, which match the variables
// registered with ExpectGetPullRequestThreadComments for a concrete expectation, or any
// variables for a default.
func (b *GetPullRequestThreadCommentsExpectation) Handle(fn func(GetPullRequestThreadCommentsVariables, http.ResponseWriter)) {
	b.register(getPullRequestThreadCommentsRawResult{fn: fn})
}

// ExpectGetPullRequestThreadComments sets up an expectation for the GetPullRequestThreadComments operation.
func (s *TestHandler) ExpectGetPullRequestThreadComments(vars GetPullRequestThreadCommentsVariables, opts ...ExpectOption) *GetPullRequestThreadCommentsExpectation {
	return &GetPullRequestThreadCommentsExpectation{
		handler: s,
		vars:    vars,
		opts:    opts,
	}
}

// DefaultGetPullRequestThreadComments returns a builder for setting the default response for the
// GetPullRequestThreadComments operation. The default is used only when no ExpectGetPullRequestThreadComments
// expectation matches an incoming request. Defaults are infinitely callable
// and never fail at cleanup. Calling DefaultGetPullRequestThreadComments replaces any previously
// registered default.
func (s *TestHandler) DefaultGetPullRequestThreadComments() *GetPullRequestThreadCommentsExpectation {
	return &GetPullRequestThreadCommentsExpectation{
		handler:   s,
		isDefault: true,
	}
}

// ResetGetPullRequestThreadComments wipes all registered expectations and the default for the
// GetPullRequestThreadComments operation, and clears any pending cleanup errors. ResetGetPullRequestThreadComments
// records an error via tb.Errorf and leaves state untouched if the handler
// has already served any request (checked handler-wide, not per-operation),
// so it is safe to call only during test setup. The served-check and the
// clear are performed atomically — no request can mark the handler served
// while a ResetGetPullRequestThreadComments is in progress.
func (s *TestHandler) ResetGetPullRequestThreadComments() {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.served {
		s.tb.Errorf("TestHandler.ResetGetPullRequestThreadComments called after handler has served at least one request")
		return
	}
	s.getPullRequestThreadCommentsExpectResponses.clear()
}
