// Code generated by github.com/willabides/gqltesthandler/cmd/gqltesthandler. DO NOT EDIT.

package ghtest

import (
	"net/http"
)

// TestHandler is a mock GraphQL HTTP handler for testing.
// Set expectations with Expect methods, then use as an http.Handler.
type TestHandler struct {
	tb      TB
	handler http.Handler

	getPullRequestReviewsExpectResponses        expectResponses[GetPullRequestReviewsVariables, getPullRequestReviewsResult]
	getPullRequestThreadsExpectResponses        expectResponses[GetPullRequestThreadsVariables, getPullRequestThreadsResult]
	getPullRequestThreadCommentsExpectResponses expectResponses[GetPullRequestThreadCommentsVariables, getPullRequestThreadCommentsResult]
}

func (s *TestHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	s.handler.ServeHTTP(w, r)
}

// NewTestHandler creates a new TestHandler for use in tests.
func NewTestHandler(tb TB) *TestHandler {
	th := &TestHandler{tb: tb}
	th.handler = &testServer{tb: tb, handler: th}
	return th
}

// getPullRequestReviewsResult is the result interface for the GetPullRequestReviews operation.
type getPullRequestReviewsResult interface {
	writeGetPullRequestReviewsResult(w http.ResponseWriter) error
}

type getPullRequestReviewsDataResult struct {
	data GetPullRequestReviewsResponse
}

func (r getPullRequestReviewsDataResult) writeGetPullRequestReviewsResult(w http.ResponseWriter) error {
	return writeGraphQLData(w, r.data)
}

type getPullRequestReviewsErrorResult struct {
	errors []GraphQLError
}

func (r getPullRequestReviewsErrorResult) writeGetPullRequestReviewsResult(w http.ResponseWriter) error {
	return writeGraphQLErrors(w, r.errors)
}

type getPullRequestReviewsRawResult struct {
	vars GetPullRequestReviewsVariables
	fn   func(GetPullRequestReviewsVariables, http.ResponseWriter)
}

func (r getPullRequestReviewsRawResult) writeGetPullRequestReviewsResult(w http.ResponseWriter) error {
	r.fn(r.vars, w)
	return nil
}

// GetPullRequestReviewsExpectation is a builder for setting the response of a GetPullRequestReviews expectation.
type GetPullRequestReviewsExpectation struct {
	handler *TestHandler
	vars    GetPullRequestReviewsVariables
	opts    []ExpectOption
}

// Respond sets the expectation to return the given data.
func (b *GetPullRequestReviewsExpectation) Respond(data GetPullRequestReviewsResponse) {
	b.handler.getPullRequestReviewsExpectResponses.expect(b.handler.tb, b.vars, nil, getPullRequestReviewsDataResult{data: data}, b.opts...)
}

// RespondError sets the expectation to return GraphQL errors.
func (b *GetPullRequestReviewsExpectation) RespondError(errors ...GraphQLError) {
	b.handler.getPullRequestReviewsExpectResponses.expect(b.handler.tb, b.vars, nil, getPullRequestReviewsErrorResult{errors: errors}, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function.
func (b *GetPullRequestReviewsExpectation) Handle(fn func(GetPullRequestReviewsVariables, http.ResponseWriter)) {
	b.handler.getPullRequestReviewsExpectResponses.expect(b.handler.tb, b.vars, nil, getPullRequestReviewsRawResult{vars: b.vars, fn: fn}, b.opts...)
}

// ExpectGetPullRequestReviews sets up an expectation for the GetPullRequestReviews operation.
func (s *TestHandler) ExpectGetPullRequestReviews(vars GetPullRequestReviewsVariables, opts ...ExpectOption) *GetPullRequestReviewsExpectation {
	return &GetPullRequestReviewsExpectation{
		handler: s,
		vars:    vars,
		opts:    opts,
	}
}

// getPullRequestThreadsResult is the result interface for the GetPullRequestThreads operation.
type getPullRequestThreadsResult interface {
	writeGetPullRequestThreadsResult(w http.ResponseWriter) error
}

type getPullRequestThreadsDataResult struct {
	data GetPullRequestThreadsResponse
}

func (r getPullRequestThreadsDataResult) writeGetPullRequestThreadsResult(w http.ResponseWriter) error {
	return writeGraphQLData(w, r.data)
}

type getPullRequestThreadsErrorResult struct {
	errors []GraphQLError
}

func (r getPullRequestThreadsErrorResult) writeGetPullRequestThreadsResult(w http.ResponseWriter) error {
	return writeGraphQLErrors(w, r.errors)
}

type getPullRequestThreadsRawResult struct {
	vars GetPullRequestThreadsVariables
	fn   func(GetPullRequestThreadsVariables, http.ResponseWriter)
}

func (r getPullRequestThreadsRawResult) writeGetPullRequestThreadsResult(w http.ResponseWriter) error {
	r.fn(r.vars, w)
	return nil
}

// GetPullRequestThreadsExpectation is a builder for setting the response of a GetPullRequestThreads expectation.
type GetPullRequestThreadsExpectation struct {
	handler *TestHandler
	vars    GetPullRequestThreadsVariables
	opts    []ExpectOption
}

// Respond sets the expectation to return the given data.
func (b *GetPullRequestThreadsExpectation) Respond(data GetPullRequestThreadsResponse) {
	b.handler.getPullRequestThreadsExpectResponses.expect(b.handler.tb, b.vars, nil, getPullRequestThreadsDataResult{data: data}, b.opts...)
}

// RespondError sets the expectation to return GraphQL errors.
func (b *GetPullRequestThreadsExpectation) RespondError(errors ...GraphQLError) {
	b.handler.getPullRequestThreadsExpectResponses.expect(b.handler.tb, b.vars, nil, getPullRequestThreadsErrorResult{errors: errors}, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function.
func (b *GetPullRequestThreadsExpectation) Handle(fn func(GetPullRequestThreadsVariables, http.ResponseWriter)) {
	b.handler.getPullRequestThreadsExpectResponses.expect(b.handler.tb, b.vars, nil, getPullRequestThreadsRawResult{vars: b.vars, fn: fn}, b.opts...)
}

// ExpectGetPullRequestThreads sets up an expectation for the GetPullRequestThreads operation.
func (s *TestHandler) ExpectGetPullRequestThreads(vars GetPullRequestThreadsVariables, opts ...ExpectOption) *GetPullRequestThreadsExpectation {
	return &GetPullRequestThreadsExpectation{
		handler: s,
		vars:    vars,
		opts:    opts,
	}
}

// getPullRequestThreadCommentsResult is the result interface for the GetPullRequestThreadComments operation.
type getPullRequestThreadCommentsResult interface {
	writeGetPullRequestThreadCommentsResult(w http.ResponseWriter) error
}

type getPullRequestThreadCommentsDataResult struct {
	data GetPullRequestThreadCommentsResponse
}

func (r getPullRequestThreadCommentsDataResult) writeGetPullRequestThreadCommentsResult(w http.ResponseWriter) error {
	return writeGraphQLData(w, r.data)
}

type getPullRequestThreadCommentsErrorResult struct {
	errors []GraphQLError
}

func (r getPullRequestThreadCommentsErrorResult) writeGetPullRequestThreadCommentsResult(w http.ResponseWriter) error {
	return writeGraphQLErrors(w, r.errors)
}

type getPullRequestThreadCommentsRawResult struct {
	vars GetPullRequestThreadCommentsVariables
	fn   func(GetPullRequestThreadCommentsVariables, http.ResponseWriter)
}

func (r getPullRequestThreadCommentsRawResult) writeGetPullRequestThreadCommentsResult(w http.ResponseWriter) error {
	r.fn(r.vars, w)
	return nil
}

// GetPullRequestThreadCommentsExpectation is a builder for setting the response of a GetPullRequestThreadComments expectation.
type GetPullRequestThreadCommentsExpectation struct {
	handler *TestHandler
	vars    GetPullRequestThreadCommentsVariables
	opts    []ExpectOption
}

// Respond sets the expectation to return the given data.
func (b *GetPullRequestThreadCommentsExpectation) Respond(data GetPullRequestThreadCommentsResponse) {
	b.handler.getPullRequestThreadCommentsExpectResponses.expect(b.handler.tb, b.vars, nil, getPullRequestThreadCommentsDataResult{data: data}, b.opts...)
}

// RespondError sets the expectation to return GraphQL errors.
func (b *GetPullRequestThreadCommentsExpectation) RespondError(errors ...GraphQLError) {
	b.handler.getPullRequestThreadCommentsExpectResponses.expect(b.handler.tb, b.vars, nil, getPullRequestThreadCommentsErrorResult{errors: errors}, b.opts...)
}

// Handle sets the expectation to invoke a custom handler function.
func (b *GetPullRequestThreadCommentsExpectation) Handle(fn func(GetPullRequestThreadCommentsVariables, http.ResponseWriter)) {
	b.handler.getPullRequestThreadCommentsExpectResponses.expect(b.handler.tb, b.vars, nil, getPullRequestThreadCommentsRawResult{vars: b.vars, fn: fn}, b.opts...)
}

// ExpectGetPullRequestThreadComments sets up an expectation for the GetPullRequestThreadComments operation.
func (s *TestHandler) ExpectGetPullRequestThreadComments(vars GetPullRequestThreadCommentsVariables, opts ...ExpectOption) *GetPullRequestThreadCommentsExpectation {
	return &GetPullRequestThreadCommentsExpectation{
		handler: s,
		vars:    vars,
		opts:    opts,
	}
}
