// Code generated by github.com/willabides/gqltesthandler/cmd/gqltesthandler. DO NOT EDIT.

package ghtest

import (
	"encoding/json"
	"net/http"
)

type testServer struct {
	tb      TB
	handler *TestHandler
}

type graphqlRequest struct {
	Query         string          `json:"query"`
	OperationName string          `json:"operationName"`
	Variables     json.RawMessage `json:"variables"`
}

func (s *testServer) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req graphqlRequest
	err := json.NewDecoder(r.Body).Decode(&req)
	if err != nil {
		writeGraphQLErrors(w, []GraphQLError{{Message: "failed to decode request: " + err.Error()}})
		return
	}

	switch req.OperationName {
	case "GetPullRequestReviews":
		var vars GetPullRequestReviewsVariables
		if len(req.Variables) > 0 {
			err = json.Unmarshal(req.Variables, &vars)
			if err != nil {
				writeGraphQLErrors(w, []GraphQLError{{Message: "failed to decode variables: " + err.Error()}})
				return
			}
		}
		resp, getErr := s.handler.getPullRequestReviewsExpectResponses.getResponse(s.tb, vars, nil)
		if getErr != nil {
			writeGraphQLErrors(w, []GraphQLError{{Message: getErr.Error()}})
			return
		}
		_ = resp.writeGetPullRequestReviewsResult(w)
	case "GetPullRequestThreads":
		var vars GetPullRequestThreadsVariables
		if len(req.Variables) > 0 {
			err = json.Unmarshal(req.Variables, &vars)
			if err != nil {
				writeGraphQLErrors(w, []GraphQLError{{Message: "failed to decode variables: " + err.Error()}})
				return
			}
		}
		resp, getErr := s.handler.getPullRequestThreadsExpectResponses.getResponse(s.tb, vars, nil)
		if getErr != nil {
			writeGraphQLErrors(w, []GraphQLError{{Message: getErr.Error()}})
			return
		}
		_ = resp.writeGetPullRequestThreadsResult(w)
	case "GetPullRequestThreadComments":
		var vars GetPullRequestThreadCommentsVariables
		if len(req.Variables) > 0 {
			err = json.Unmarshal(req.Variables, &vars)
			if err != nil {
				writeGraphQLErrors(w, []GraphQLError{{Message: "failed to decode variables: " + err.Error()}})
				return
			}
		}
		resp, getErr := s.handler.getPullRequestThreadCommentsExpectResponses.getResponse(s.tb, vars, nil)
		if getErr != nil {
			writeGraphQLErrors(w, []GraphQLError{{Message: getErr.Error()}})
			return
		}
		_ = resp.writeGetPullRequestThreadCommentsResult(w)
	default:
		writeGraphQLErrors(w, []GraphQLError{{Message: "unknown operation: " + req.OperationName}})
	}
}

func writeGraphQLData(w http.ResponseWriter, data any) error {
	w.Header().Set("Content-Type", "application/json")
	return json.NewEncoder(w).Encode(map[string]any{"data": data})
}

func writeGraphQLErrors(w http.ResponseWriter, errors []GraphQLError) error {
	w.Header().Set("Content-Type", "application/json")
	return json.NewEncoder(w).Encode(map[string]any{"errors": errors})
}
