// Code generated by github.com/willabides/gqltesthandler/cmd/gqltesthandler. DO NOT EDIT.

package ghtest

import "encoding/json"

// GraphQLError represents a GraphQL error in the response.
type GraphQLError struct {
	Message    string         `json:"message"`
	Path       []any          `json:"path,omitempty"`
	Extensions map[string]any `json:"extensions,omitempty"`
}

type PullRequestReviewState string

const (
	PullRequestReviewStateApproved          PullRequestReviewState = "APPROVED"
	PullRequestReviewStateChanges_requested PullRequestReviewState = "CHANGES_REQUESTED"
	PullRequestReviewStateCommented         PullRequestReviewState = "COMMENTED"
	PullRequestReviewStateDismissed         PullRequestReviewState = "DISMISSED"
	PullRequestReviewStatePending           PullRequestReviewState = "PENDING"
)

type DiffSide string

const (
	DiffSideLeft  DiffSide = "LEFT"
	DiffSideRight DiffSide = "RIGHT"
)

type PullRequestReviewThreadSubjectType string

const (
	PullRequestReviewThreadSubjectTypeFile PullRequestReviewThreadSubjectType = "FILE"
	PullRequestReviewThreadSubjectTypeLine PullRequestReviewThreadSubjectType = "LINE"
)

type GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesAuthorTypename string

const (
	GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesAuthorTypenameBot                   GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesAuthorTypename = "Bot"
	GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesAuthorTypenameEnterpriseUserAccount GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesAuthorTypename = "EnterpriseUserAccount"
	GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesAuthorTypenameMannequin             GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesAuthorTypename = "Mannequin"
	GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesAuthorTypenameOrganization          GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesAuthorTypename = "Organization"
	GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesAuthorTypenameUser                  GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesAuthorTypename = "User"
)

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesAuthorTypename string

const (
	GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesAuthorTypenameBot                   GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesAuthorTypename = "Bot"
	GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesAuthorTypenameEnterpriseUserAccount GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesAuthorTypename = "EnterpriseUserAccount"
	GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesAuthorTypenameMannequin             GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesAuthorTypename = "Mannequin"
	GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesAuthorTypenameOrganization          GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesAuthorTypename = "Organization"
	GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesAuthorTypenameUser                  GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesAuthorTypename = "User"
)

type GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesAuthorTypename string

const (
	GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesAuthorTypenameBot                   GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesAuthorTypename = "Bot"
	GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesAuthorTypenameEnterpriseUserAccount GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesAuthorTypename = "EnterpriseUserAccount"
	GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesAuthorTypenameMannequin             GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesAuthorTypename = "Mannequin"
	GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesAuthorTypenameOrganization          GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesAuthorTypename = "Organization"
	GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesAuthorTypenameUser                  GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesAuthorTypename = "User"
)

// GetPullRequestReviewsVariables contains the variables for the GetPullRequestReviews operation.
type GetPullRequestReviewsVariables struct {
	Owner      string  `json:"owner"`
	Repo       string  `json:"repo"`
	PullNumber int     `json:"pullNumber"`
	Cursor     *string `json:"cursor"`
}

// GetPullRequestReviewsResponse contains the data returned by the GetPullRequestReviews operation.
type GetPullRequestReviewsResponse struct {
	Repository *GetPullRequestReviewsResponseRepository `json:"repository"`
}

type GetPullRequestReviewsResponseRepository struct {
	PullRequest *GetPullRequestReviewsResponseRepositoryPullRequest `json:"pullRequest"`
}

type GetPullRequestReviewsResponseRepositoryPullRequest struct {
	Url     any                                                        `json:"url"`
	Reviews *GetPullRequestReviewsResponseRepositoryPullRequestReviews `json:"reviews"`
}

type GetPullRequestReviewsResponseRepositoryPullRequestReviews struct {
	Nodes    []*GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodes `json:"nodes"`
	PageInfo GetPullRequestReviewsResponseRepositoryPullRequestReviewsPageInfo `json:"pageInfo"`
}

type GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodes struct {
	Url            any                                                                   `json:"url"`
	FullDatabaseId *any                                                                  `json:"fullDatabaseId"`
	Author         *GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesAuthor `json:"author"`
	Body           string                                                                `json:"body"`
	State          PullRequestReviewState                                                `json:"state"`
	CreatedAt      any                                                                   `json:"createdAt"`
	SubmittedAt    *any                                                                  `json:"submittedAt"`
	Commit         *GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesCommit `json:"commit"`
}

type GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesAuthor struct {
	Typename GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesAuthorTypename `json:"__typename,omitempty"`
	Url      any                                                                          `json:"url"`
}

type GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesCommit struct {
	Oid any `json:"oid"`
}

type GetPullRequestReviewsResponseRepositoryPullRequestReviewsPageInfo struct {
	EndCursor   *string `json:"endCursor"`
	HasNextPage bool    `json:"hasNextPage"`
}

// GetPullRequestThreadsVariables contains the variables for the GetPullRequestThreads operation.
type GetPullRequestThreadsVariables struct {
	Owner          string  `json:"owner"`
	Repo           string  `json:"repo"`
	PullNumber     int     `json:"pullNumber"`
	ThreadsCursor  *string `json:"threadsCursor"`
	CommentsCursor *string `json:"commentsCursor"`
}

// GetPullRequestThreadsResponse contains the data returned by the GetPullRequestThreads operation.
type GetPullRequestThreadsResponse struct {
	Repository *GetPullRequestThreadsResponseRepository `json:"repository"`
}

type GetPullRequestThreadsResponseRepository struct {
	PullRequest *GetPullRequestThreadsResponseRepositoryPullRequest `json:"pullRequest"`
}

type GetPullRequestThreadsResponseRepositoryPullRequest struct {
	ReviewThreads GetPullRequestThreadsResponseRepositoryPullRequestReviewThreads `json:"reviewThreads"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreads struct {
	Nodes    []*GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodes `json:"nodes"`
	PageInfo GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsPageInfo `json:"pageInfo"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodes struct {
	ID                string                                                                          `json:"id"`
	IsResolved        bool                                                                            `json:"isResolved"`
	IsOutdated        bool                                                                            `json:"isOutdated"`
	ResolvedBy        *GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesResolvedBy `json:"resolvedBy"`
	Path              string                                                                          `json:"path"`
	Line              *int                                                                            `json:"line"`
	StartLine         *int                                                                            `json:"startLine"`
	OriginalLine      *int                                                                            `json:"originalLine"`
	OriginalStartLine *int                                                                            `json:"originalStartLine"`
	DiffSide          DiffSide                                                                        `json:"diffSide"`
	StartDiffSide     *DiffSide                                                                       `json:"startDiffSide"`
	SubjectType       PullRequestReviewThreadSubjectType                                              `json:"subjectType"`
	Comments          GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesComments    `json:"comments"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesResolvedBy struct {
	Url any `json:"url"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesComments struct {
	Nodes    []*GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodes `json:"nodes"`
	PageInfo GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsPageInfo `json:"pageInfo"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodes struct {
	FullDatabaseId    *any                                                                                                `json:"fullDatabaseId"`
	Author            *GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesAuthor            `json:"author"`
	Body              string                                                                                              `json:"body"`
	CreatedAt         any                                                                                                 `json:"createdAt"`
	DiffHunk          string                                                                                              `json:"diffHunk"`
	Commit            *GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesCommit            `json:"commit"`
	OriginalCommit    *GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesOriginalCommit    `json:"originalCommit"`
	PullRequestReview *GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesPullRequestReview `json:"pullRequestReview"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesAuthor struct {
	Typename GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesAuthorTypename `json:"__typename,omitempty"`
	Url      any                                                                                             `json:"url"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesCommit struct {
	Oid any `json:"oid"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesOriginalCommit struct {
	Oid any `json:"oid"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesPullRequestReview struct {
	FullDatabaseId *any `json:"fullDatabaseId"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsPageInfo struct {
	EndCursor   *string `json:"endCursor"`
	HasNextPage bool    `json:"hasNextPage"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsPageInfo struct {
	EndCursor   *string `json:"endCursor"`
	HasNextPage bool    `json:"hasNextPage"`
}

// GetPullRequestThreadCommentsVariables contains the variables for the GetPullRequestThreadComments operation.
type GetPullRequestThreadCommentsVariables struct {
	ThreadID       string  `json:"threadID"`
	CommentsCursor *string `json:"commentsCursor"`
}

// GetPullRequestThreadCommentsResponse contains the data returned by the GetPullRequestThreadComments operation.
type GetPullRequestThreadCommentsResponse struct {
	Node GetPullRequestThreadCommentsResponseNode `json:"node"`
}

type GetPullRequestThreadCommentsResponseNode interface {
	isGetPullRequestThreadCommentsResponseNode()
}

type GetPullRequestThreadCommentsResponseNodePullRequestReviewThread struct {
	Comments GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadComments `json:"comments"`
}

func (GetPullRequestThreadCommentsResponseNodePullRequestReviewThread) isGetPullRequestThreadCommentsResponseNode() {
}

func (v GetPullRequestThreadCommentsResponseNodePullRequestReviewThread) MarshalJSON() ([]byte, error) {
	type alias GetPullRequestThreadCommentsResponseNodePullRequestReviewThread
	return json.Marshal(struct {
		Typename string `json:"__typename"`
		alias
	}{
		Typename: "PullRequestReviewThread",
		alias:    alias(v),
	})
}

type GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadComments struct {
	Nodes    []*GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodes `json:"nodes"`
	PageInfo GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsPageInfo `json:"pageInfo"`
}

type GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodes struct {
	FullDatabaseId    *any                                                                                           `json:"fullDatabaseId"`
	Author            *GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesAuthor            `json:"author"`
	Body              string                                                                                         `json:"body"`
	CreatedAt         any                                                                                            `json:"createdAt"`
	DiffHunk          string                                                                                         `json:"diffHunk"`
	Commit            *GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesCommit            `json:"commit"`
	OriginalCommit    *GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesOriginalCommit    `json:"originalCommit"`
	PullRequestReview *GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesPullRequestReview `json:"pullRequestReview"`
}

type GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesAuthor struct {
	Typename GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesAuthorTypename `json:"__typename,omitempty"`
	Url      any                                                                                        `json:"url"`
}

type GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesCommit struct {
	Oid any `json:"oid"`
}

type GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesOriginalCommit struct {
	Oid any `json:"oid"`
}

type GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsNodesPullRequestReview struct {
	FullDatabaseId *any `json:"fullDatabaseId"`
}

type GetPullRequestThreadCommentsResponseNodePullRequestReviewThreadCommentsPageInfo struct {
	EndCursor   *string `json:"endCursor"`
	HasNextPage bool    `json:"hasNextPage"`
}
