// Code generated by github.com/willabides/gqltesthandler/cmd/gqltesthandler. DO NOT EDIT.

package ghtest

// GraphQLError represents a GraphQL error in the response.
type GraphQLError struct {
	Message    string         `json:"message"`
	Path       []any          `json:"path,omitempty"`
	Extensions map[string]any `json:"extensions,omitempty"`
}

type PullRequestReviewState string

const (
	PullRequestReviewStateApproved          PullRequestReviewState = "APPROVED"
	PullRequestReviewStateChanges_requested PullRequestReviewState = "CHANGES_REQUESTED"
	PullRequestReviewStateCommented         PullRequestReviewState = "COMMENTED"
	PullRequestReviewStateDismissed         PullRequestReviewState = "DISMISSED"
	PullRequestReviewStatePending           PullRequestReviewState = "PENDING"
)

type DiffSide string

const (
	DiffSideLeft  DiffSide = "LEFT"
	DiffSideRight DiffSide = "RIGHT"
)

type PullRequestReviewThreadSubjectType string

const (
	PullRequestReviewThreadSubjectTypeFile PullRequestReviewThreadSubjectType = "FILE"
	PullRequestReviewThreadSubjectTypeLine PullRequestReviewThreadSubjectType = "LINE"
)

// GetPullRequestReviewsVariables contains the variables for the GetPullRequestReviews operation.
type GetPullRequestReviewsVariables struct {
	Owner      string  `json:"owner"`
	Repo       string  `json:"repo"`
	PullNumber int     `json:"pullNumber"`
	Cursor     *string `json:"cursor"`
}

// GetPullRequestReviewsResponse contains the data returned by the GetPullRequestReviews operation.
type GetPullRequestReviewsResponse struct {
	Repository *GetPullRequestReviewsResponseRepository `json:"repository"`
}

type GetPullRequestReviewsResponseRepository struct {
	PullRequest *GetPullRequestReviewsResponseRepositoryPullRequest `json:"pullRequest"`
}

type GetPullRequestReviewsResponseRepositoryPullRequest struct {
	Url     any                                                        `json:"url"`
	Reviews *GetPullRequestReviewsResponseRepositoryPullRequestReviews `json:"reviews"`
}

type GetPullRequestReviewsResponseRepositoryPullRequestReviews struct {
	Nodes    []*GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodes `json:"nodes"`
	PageInfo GetPullRequestReviewsResponseRepositoryPullRequestReviewsPageInfo `json:"pageInfo"`
}

type GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodes struct {
	Url            any                                                                   `json:"url"`
	FullDatabaseId *any                                                                  `json:"fullDatabaseId"`
	Author         *GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesAuthor `json:"author"`
	Body           string                                                                `json:"body"`
	State          PullRequestReviewState                                                `json:"state"`
	CreatedAt      any                                                                   `json:"createdAt"`
	SubmittedAt    *any                                                                  `json:"submittedAt"`
	Commit         *GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesCommit `json:"commit"`
}

type GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesAuthor struct {
	Url any `json:"url"`
}

type GetPullRequestReviewsResponseRepositoryPullRequestReviewsNodesCommit struct {
	Oid any `json:"oid"`
}

type GetPullRequestReviewsResponseRepositoryPullRequestReviewsPageInfo struct {
	EndCursor   *string `json:"endCursor"`
	HasNextPage bool    `json:"hasNextPage"`
}

// GetPullRequestThreadsVariables contains the variables for the GetPullRequestThreads operation.
type GetPullRequestThreadsVariables struct {
	Owner          string  `json:"owner"`
	Repo           string  `json:"repo"`
	PullNumber     int     `json:"pullNumber"`
	ThreadsCursor  *string `json:"threadsCursor"`
	CommentsCursor *string `json:"commentsCursor"`
}

// GetPullRequestThreadsResponse contains the data returned by the GetPullRequestThreads operation.
type GetPullRequestThreadsResponse struct {
	Repository *GetPullRequestThreadsResponseRepository `json:"repository"`
}

type GetPullRequestThreadsResponseRepository struct {
	PullRequest *GetPullRequestThreadsResponseRepositoryPullRequest `json:"pullRequest"`
}

type GetPullRequestThreadsResponseRepositoryPullRequest struct {
	ReviewThreads GetPullRequestThreadsResponseRepositoryPullRequestReviewThreads `json:"reviewThreads"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreads struct {
	Nodes    []*GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodes `json:"nodes"`
	PageInfo GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsPageInfo `json:"pageInfo"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodes struct {
	ID                string                                                                          `json:"id"`
	IsResolved        bool                                                                            `json:"isResolved"`
	IsOutdated        bool                                                                            `json:"isOutdated"`
	ResolvedBy        *GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesResolvedBy `json:"resolvedBy"`
	Path              string                                                                          `json:"path"`
	Line              *int                                                                            `json:"line"`
	StartLine         *int                                                                            `json:"startLine"`
	OriginalLine      *int                                                                            `json:"originalLine"`
	OriginalStartLine *int                                                                            `json:"originalStartLine"`
	DiffSide          DiffSide                                                                        `json:"diffSide"`
	StartDiffSide     *DiffSide                                                                       `json:"startDiffSide"`
	SubjectType       PullRequestReviewThreadSubjectType                                              `json:"subjectType"`
	Comments          GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesComments    `json:"comments"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesResolvedBy struct {
	Url any `json:"url"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesComments struct {
	Nodes    []*GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodes `json:"nodes"`
	PageInfo GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsPageInfo `json:"pageInfo"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodes struct {
	FullDatabaseId    *any                                                                                                `json:"fullDatabaseId"`
	Author            *GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesAuthor            `json:"author"`
	Body              string                                                                                              `json:"body"`
	CreatedAt         any                                                                                                 `json:"createdAt"`
	DiffHunk          string                                                                                              `json:"diffHunk"`
	Commit            *GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesCommit            `json:"commit"`
	OriginalCommit    *GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesOriginalCommit    `json:"originalCommit"`
	PullRequestReview *GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesPullRequestReview `json:"pullRequestReview"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesAuthor struct {
	Url any `json:"url"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesCommit struct {
	Oid any `json:"oid"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesOriginalCommit struct {
	Oid any `json:"oid"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsNodesPullRequestReview struct {
	FullDatabaseId *any `json:"fullDatabaseId"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsNodesCommentsPageInfo struct {
	EndCursor   *string `json:"endCursor"`
	HasNextPage bool    `json:"hasNextPage"`
}

type GetPullRequestThreadsResponseRepositoryPullRequestReviewThreadsPageInfo struct {
	EndCursor   *string `json:"endCursor"`
	HasNextPage bool    `json:"hasNextPage"`
}

// GetPullRequestThreadCommentsVariables contains the variables for the GetPullRequestThreadComments operation.
type GetPullRequestThreadCommentsVariables struct {
	ThreadID       string  `json:"threadID"`
	CommentsCursor *string `json:"commentsCursor"`
}

// GetPullRequestThreadCommentsResponse contains the data returned by the GetPullRequestThreadComments operation.
type GetPullRequestThreadCommentsResponse struct {
	Node *GetPullRequestThreadCommentsResponseNode `json:"node"`
}

type GetPullRequestThreadCommentsResponseNode struct {
	Comments GetPullRequestThreadCommentsResponseNodeComments `json:"comments"`
}

type GetPullRequestThreadCommentsResponseNodeComments struct {
	Nodes    []*GetPullRequestThreadCommentsResponseNodeCommentsNodes `json:"nodes"`
	PageInfo GetPullRequestThreadCommentsResponseNodeCommentsPageInfo `json:"pageInfo"`
}

type GetPullRequestThreadCommentsResponseNodeCommentsNodes struct {
	FullDatabaseId    *any                                                                    `json:"fullDatabaseId"`
	Author            *GetPullRequestThreadCommentsResponseNodeCommentsNodesAuthor            `json:"author"`
	Body              string                                                                  `json:"body"`
	CreatedAt         any                                                                     `json:"createdAt"`
	DiffHunk          string                                                                  `json:"diffHunk"`
	Commit            *GetPullRequestThreadCommentsResponseNodeCommentsNodesCommit            `json:"commit"`
	OriginalCommit    *GetPullRequestThreadCommentsResponseNodeCommentsNodesOriginalCommit    `json:"originalCommit"`
	PullRequestReview *GetPullRequestThreadCommentsResponseNodeCommentsNodesPullRequestReview `json:"pullRequestReview"`
}

type GetPullRequestThreadCommentsResponseNodeCommentsNodesAuthor struct {
	Url any `json:"url"`
}

type GetPullRequestThreadCommentsResponseNodeCommentsNodesCommit struct {
	Oid any `json:"oid"`
}

type GetPullRequestThreadCommentsResponseNodeCommentsNodesOriginalCommit struct {
	Oid any `json:"oid"`
}

type GetPullRequestThreadCommentsResponseNodeCommentsNodesPullRequestReview struct {
	FullDatabaseId *any `json:"fullDatabaseId"`
}

type GetPullRequestThreadCommentsResponseNodeCommentsPageInfo struct {
	EndCursor   *string `json:"endCursor"`
	HasNextPage bool    `json:"hasNextPage"`
}
