// Code generated by github.com/gqlgo/gqlgenc, DO NOT EDIT.

package client

import (
	"context"

	"github.com/gqlgo/gqlgenc/clientv2"
)

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) *Client {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type GetUser_User struct {
	Email string "json:\"email\" graphql:\"email\""
	ID    string "json:\"id\" graphql:\"id\""
	Name  string "json:\"name\" graphql:\"name\""
}

func (t *GetUser_User) GetEmail() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Email
}
func (t *GetUser_User) GetID() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.ID
}
func (t *GetUser_User) GetName() string {
	if t == nil {
		t = &GetUser_User{}
	}
	return t.Name
}

type CreateUser_CreateUser struct {
	Email string "json:\"email\" graphql:\"email\""
	ID    string "json:\"id\" graphql:\"id\""
	Name  string "json:\"name\" graphql:\"name\""
}

func (t *CreateUser_CreateUser) GetEmail() string {
	if t == nil {
		t = &CreateUser_CreateUser{}
	}
	return t.Email
}
func (t *CreateUser_CreateUser) GetID() string {
	if t == nil {
		t = &CreateUser_CreateUser{}
	}
	return t.ID
}
func (t *CreateUser_CreateUser) GetName() string {
	if t == nil {
		t = &CreateUser_CreateUser{}
	}
	return t.Name
}

type GetUser struct {
	User *GetUser_User "json:\"user,omitempty\" graphql:\"user\""
}

func (t *GetUser) GetUser() *GetUser_User {
	if t == nil {
		t = &GetUser{}
	}
	return t.User
}

type CreateUser struct {
	CreateUser CreateUser_CreateUser "json:\"createUser\" graphql:\"createUser\""
}

func (t *CreateUser) GetCreateUser() *CreateUser_CreateUser {
	if t == nil {
		t = &CreateUser{}
	}
	return &t.CreateUser
}

const GetUserDocument = `query GetUser ($id: ID!) {
	user(id: $id) {
		id
		name
		email
	}
}
`

func (c *Client) GetUser(ctx context.Context, id string, interceptors ...clientv2.RequestInterceptor) (*GetUser, error) {
	vars := map[string]any{
		"id": id,
	}

	var res GetUser
	if err := c.Client.Post(ctx, "GetUser", GetUserDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const CreateUserDocument = `mutation CreateUser ($input: CreateUserInput!) {
	createUser(input: $input) {
		id
		name
		email
	}
}
`

func (c *Client) CreateUser(ctx context.Context, input CreateUserInput, interceptors ...clientv2.RequestInterceptor) (*CreateUser, error) {
	vars := map[string]any{
		"input": input,
	}

	var res CreateUser
	if err := c.Client.Post(ctx, "CreateUser", CreateUserDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetUserDocument:    "GetUser",
	CreateUserDocument: "CreateUser",
}
