#!/bin/sh
#/ script/gqltesthandler builds and runs the project with the given arguments.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

go build -o bin/gqltesthandler ./cmd/gqltesthandler

exec bin/gqltesthandler "$@"
