#!/bin/sh
#/ script/test runs tests on the project.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

go test -race -covermode=atomic ./...

for dir in example/*/; do
  [ -f "$dir/go.mod" ] || continue
  echo "testing $dir"
  (cd "$dir" && go test -race -covermode=atomic ./...)
done
